/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Description;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Ticket
 */
public class TicketTest {
    private final Ticket model = new Ticket();

    /**
     * Model tests for Ticket
     */
    @Test
    public void testTicket() {
        // TODO: test Ticket
    }

    /**
     * Test the property 'ticketID'
     */
    @Test
    public void ticketIDTest() {
        // TODO: test ticketID
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'assignedUser'
     */
    @Test
    public void assignedUserTest() {
        // TODO: test assignedUser
    }

    /**
     * Test the property 'descriptions'
     */
    @Test
    public void descriptionsTest() {
        // TODO: test descriptions
    }

}
