/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.uqac.tickets.client.api;

import com.uqac.tickets.client.model.NewTicket;
import com.uqac.tickets.client.model.Ticket;
import com.uqac.tickets.client.model.UpdateTicket;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TicketsApi
 */
@Disabled
class TicketsApiTest {

    private final TicketsApi api = new TicketsApi();

    
    /**
     * Liste tous les tickets
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void ticketsGetTest() {

        List<Ticket> response = api.ticketsGet();

        // TODO: test validations
    }
    
    /**
     * Récupère un ticket par ID
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void ticketsIdGetTest() {
        Integer id = null;

        Ticket response = api.ticketsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Met à jour un ticket (statut, priorité, assignation)
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void ticketsIdPutTest() {
        Integer id = null;
        UpdateTicket updateTicket = null;

        Ticket response = api.ticketsIdPut(id, updateTicket);

        // TODO: test validations
    }
    
    /**
     * Crée un nouveau ticket
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void ticketsPostTest() {
        NewTicket newTicket = null;

        Ticket response = api.ticketsPost(newTicket);

        // TODO: test validations
    }
    
}
