/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.uqac.tickets.client.api;

import com.uqac.tickets.client.model.NewUser;
import com.uqac.tickets.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Liste tous les utilisateurs
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void usersGetTest() {

        List<User> response = api.usersGet();

        // TODO: test validations
    }
    
    /**
     * Crée un nouvel utilisateur
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void usersPostTest() {
        NewUser newUser = null;

        User response = api.usersPost(newUser);

        // TODO: test validations
    }
    
}
