/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.NewTicket;
import org.openapitools.client.model.Ticket;
import org.openapitools.client.model.UpdateTicket;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TicketsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TicketsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TicketsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for ticketsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ticketsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return ticketsGetCall(_callback);

    }

    /**
     * Liste tous les tickets
     * 
     * @return List&lt;Ticket&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets </td><td>  -  </td></tr>
     </table>
     */
    public List<Ticket> ticketsGet() throws ApiException {
        ApiResponse<List<Ticket>> localVarResp = ticketsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Liste tous les tickets
     * 
     * @return ApiResponse&lt;List&lt;Ticket&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Ticket>> ticketsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = ticketsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<Ticket>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Liste tous les tickets (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsGetAsync(final ApiCallback<List<Ticket>> _callback) throws ApiException {

        okhttp3.Call localVarCall = ticketsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<Ticket>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ticketsIdGet
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ticket introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsIdGetCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ticketsIdGetValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling ticketsIdGet(Async)");
        }

        return ticketsIdGetCall(id, _callback);

    }

    /**
     * Récupère un ticket par ID
     * 
     * @param id  (required)
     * @return Ticket
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ticket introuvable </td><td>  -  </td></tr>
     </table>
     */
    public Ticket ticketsIdGet(Integer id) throws ApiException {
        ApiResponse<Ticket> localVarResp = ticketsIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Récupère un ticket par ID
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Ticket&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ticket introuvable </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Ticket> ticketsIdGetWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = ticketsIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Récupère un ticket par ID (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ticket introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsIdGetAsync(Integer id, final ApiCallback<Ticket> _callback) throws ApiException {

        okhttp3.Call localVarCall = ticketsIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ticketsIdPut
     * @param id  (required)
     * @param updateTicket  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket mis à jour </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsIdPutCall(Integer id, UpdateTicket updateTicket, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateTicket;

        // create path and map variables
        String localVarPath = "/tickets/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ticketsIdPutValidateBeforeCall(Integer id, UpdateTicket updateTicket, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling ticketsIdPut(Async)");
        }

        // verify the required parameter 'updateTicket' is set
        if (updateTicket == null) {
            throw new ApiException("Missing the required parameter 'updateTicket' when calling ticketsIdPut(Async)");
        }

        return ticketsIdPutCall(id, updateTicket, _callback);

    }

    /**
     * Met à jour un ticket (statut, priorité, assignation)
     * 
     * @param id  (required)
     * @param updateTicket  (required)
     * @return Ticket
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket mis à jour </td><td>  -  </td></tr>
     </table>
     */
    public Ticket ticketsIdPut(Integer id, UpdateTicket updateTicket) throws ApiException {
        ApiResponse<Ticket> localVarResp = ticketsIdPutWithHttpInfo(id, updateTicket);
        return localVarResp.getData();
    }

    /**
     * Met à jour un ticket (statut, priorité, assignation)
     * 
     * @param id  (required)
     * @param updateTicket  (required)
     * @return ApiResponse&lt;Ticket&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket mis à jour </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Ticket> ticketsIdPutWithHttpInfo(Integer id, UpdateTicket updateTicket) throws ApiException {
        okhttp3.Call localVarCall = ticketsIdPutValidateBeforeCall(id, updateTicket, null);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Met à jour un ticket (statut, priorité, assignation) (asynchronously)
     * 
     * @param id  (required)
     * @param updateTicket  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket mis à jour </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsIdPutAsync(Integer id, UpdateTicket updateTicket, final ApiCallback<Ticket> _callback) throws ApiException {

        okhttp3.Call localVarCall = ticketsIdPutValidateBeforeCall(id, updateTicket, _callback);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ticketsPost
     * @param newTicket  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsPostCall(NewTicket newTicket, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = newTicket;

        // create path and map variables
        String localVarPath = "/tickets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ticketsPostValidateBeforeCall(NewTicket newTicket, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'newTicket' is set
        if (newTicket == null) {
            throw new ApiException("Missing the required parameter 'newTicket' when calling ticketsPost(Async)");
        }

        return ticketsPostCall(newTicket, _callback);

    }

    /**
     * Crée un nouveau ticket
     * 
     * @param newTicket  (required)
     * @return Ticket
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé </td><td>  -  </td></tr>
     </table>
     */
    public Ticket ticketsPost(NewTicket newTicket) throws ApiException {
        ApiResponse<Ticket> localVarResp = ticketsPostWithHttpInfo(newTicket);
        return localVarResp.getData();
    }

    /**
     * Crée un nouveau ticket
     * 
     * @param newTicket  (required)
     * @return ApiResponse&lt;Ticket&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Ticket> ticketsPostWithHttpInfo(NewTicket newTicket) throws ApiException {
        okhttp3.Call localVarCall = ticketsPostValidateBeforeCall(newTicket, null);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Crée un nouveau ticket (asynchronously)
     * 
     * @param newTicket  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ticketsPostAsync(NewTicket newTicket, final ApiCallback<Ticket> _callback) throws ApiException {

        okhttp3.Call localVarCall = ticketsPostValidateBeforeCall(newTicket, _callback);
        Type localVarReturnType = new TypeToken<Ticket>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
