/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.NewTicket;
import io.swagger.client.model.Ticket;
import io.swagger.client.model.UpdateTicket;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TicketsApi
 */
@Ignore
public class TicketsApiTest {

    private final TicketsApi api = new TicketsApi();

    /**
     * Liste tous les tickets
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ticketsGetTest() throws Exception {
        List<Ticket> response = api.ticketsGet();

        // TODO: test validations
    }
    /**
     * Récupère un ticket par ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ticketsIdGetTest() throws Exception {
        Integer id = null;
        Ticket response = api.ticketsIdGet(id);

        // TODO: test validations
    }
    /**
     * Met à jour un ticket (statut, priorité, assignation)
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ticketsIdPutTest() throws Exception {
        UpdateTicket body = null;
        Integer id = null;
        Ticket response = api.ticketsIdPut(body, id);

        // TODO: test validations
    }
    /**
     * Crée un nouveau ticket
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ticketsPostTest() throws Exception {
        NewTicket body = null;
        Ticket response = api.ticketsPost(body);

        // TODO: test validations
    }
}
