/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.NewUser;
import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Liste tous les utilisateurs
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void usersGetTest() throws Exception {
        List<User> response = api.usersGet();

        // TODO: test validations
    }
    /**
     * Crée un nouvel utilisateur
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void usersPostTest() throws Exception {
        NewUser body = null;
        User response = api.usersPost(body);

        // TODO: test validations
    }
}
