/*
 * Système de gestion de tickets - UQAC
 * API REST pour la gestion de tickets (Lab 4 - Architecture des logiciels). Permet aux utilisateurs de créer, consulter, et mettre à jour des tickets, et aux administrateurs de les assigner, commenter ou fermer. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.NewTicket;
import org.openapitools.client.model.Ticket;
import org.openapitools.client.model.UpdateTicket;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TicketsApi
 */
@Disabled
public class TicketsApiTest {

    private final TicketsApi api = new TicketsApi();

    /**
     * Liste tous les tickets
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ticketsGetTest() throws ApiException {
        List<Ticket> response = api.ticketsGet();
        // TODO: test validations
    }

    /**
     * Récupère un ticket par ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ticketsIdGetTest() throws ApiException {
        Integer id = null;
        Ticket response = api.ticketsIdGet(id);
        // TODO: test validations
    }

    /**
     * Met à jour un ticket (statut, priorité, assignation)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ticketsIdPutTest() throws ApiException {
        Integer id = null;
        UpdateTicket updateTicket = null;
        Ticket response = api.ticketsIdPut(id, updateTicket);
        // TODO: test validations
    }

    /**
     * Crée un nouveau ticket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ticketsPostTest() throws ApiException {
        NewTicket newTicket = null;
        Ticket response = api.ticketsPost(newTicket);
        // TODO: test validations
    }

}
